# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d396851ec25bd4f1294fe3d048a2c66695dcd86c8ca310f4cba20b4bd4db139e008e7bc4d49e6bf873d02a99b962f0143e238fda5509c11022b3e34472df0d16

test:
  secret_key_base: dbe748eb96424adc4d6a5eeb82997fb9382434b09c1162d75dd3f87716fd8b2e555be1605411eb99c541d3022dcc68b6b0be9876016adf2277026a97cd5b6ccf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
